### ISSUE TITLE
F1 23 support hit and miss

### ISSUE THREAD

**Issue by BrokenHypocrite** [EgoEngineModding/Ego-Engine-Modding#74]
Hello. Fantastic tool. I am currently having trouble with the ERP Archiver. Particularly exporting XML files from F1 23. It work fine for me in F1 22, but F1 23 doesn't even display any available XML files for export.  I have a friend in Europe that isn't having any trouble at all with F1 23. I have tried manually setting my F1 23 directory in the .config file, but that doesn't change anything. I have also tried this tool on 3 different computers and all have the same result with F1 23. Any idea what the problem might be? If it didn't work for others I would assume we just nee to wait for an update, but since others can use it without issue I'm hoping it's just a user error on my part, but I can't figure out for the life of me what I am doing wrong or where the problem comes from.

Thanks for the help!

**Comment by ptasev** [comment]
I don't own the game so I'll need a sample erp file to investigate. Also, show an image of the xml files that show up in the app for others.

**Comment by BrokenHypocrite** [comment]
Thanks for the quick response. You can find the tyrecompounds.erp file from F1 23 here:
https://github.com/BrokenHypocrite/tyrecompounds

There is also an image in there from my friend that shows there is one XML file there, and it exports just fine. When I open this .erp file with the Archiver that XML tab is blank. If I open the equivalent file in F1 22 I have no problem exporting the XML file with your tool. Thanks for the help!

**Comment by BrokenHypocrite** [comment]
Opps, didn't mean to close it.

**Comment by ptasev** [comment]
I looked into it and it will be supported in the next version. Not sure when it'll release yet. Your friend probably has a modified version of the app that supports it.

**Comment by BrokenHypocrite** [comment]
Strange, he is using 9.0, unedited. He even shared it with me so we knew we had the same version. But that's okay. I'll wait for the next version. Again, appreciate your tools massively. Thanks for looking into it.

**Comment by ptasev** [comment]
Version 9.1 has been released. Should work as expected now.

**Comment by borjarai** [comment]
With this version 9.1. I have been able to export the file, modify it, and import it again but when I tried to save it, it gave me an error. I was denied access to the archive.
