### ISSUE TITLE
'Could not find resource' on any file

### ISSUE THREAD

**Issue by virtual-voyage** [EgoEngineModding/Ego-Engine-Modding#75]
With any ERP file on the F1 23 game, all of the files show the error that it 'could not find resource'. 
![Issue](https://github.com/ptasev/Ego-Engine-Modding/assets/103288627/cbf7318d-1586-4d55-bfe9-cdcf5e3c7d70)

**Comment by ptasev** [comment]
You'll have to send me sample files for me to look into since I don't own the game.

**Comment by virtual-voyage** [comment]
[2023-redbull_sergio_perez.zip](https://github.com/ptasev/Ego-Engine-Modding/files/11749709/2023-redbull_sergio_perez.zip)
[redbull.zip](https://github.com/ptasev/Ego-Engine-Modding/files/11749722/redbull.zip)

some zipped files of a character file and a vehicle file, let me know if you need more

**Comment by ptasev** [comment]
Can you send me file `character_package/drivers/male/2023-redbull_sergio_perez/textures/sergio_perez_cap_d.tif.2023.mipmaps`?

**Comment by virtual-voyage** [comment]
[2023-redbull_sergio_perez.zip](https://github.com/ptasev/Ego-Engine-Modding/files/11750740/2023-redbull_sergio_perez.zip)

had to send the whole zipped file since github doesn't support specific mipmaps, hope that's ok

**Comment by FabCande** [comment]
i've the same error

**Comment by ptasev** [comment]
Version 9.1 has been released. Should work as expected now.
